[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
decorations = "none"

padding.x = 5
padding.y = 5

opacity = 0.65
blur = true

[font]

normal.family = "FiraCode Nerd Font"
size  = 14

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session"]
